#This workflow will install Python dependencies, run tests and lint with a variety of Python versions
#For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Construir CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-última
    strategy:
      matrix:
        python-version:
          - 3.8
    steps:
      - 
        name: Configurando variables env
        run: echo Configuración de variables env
        env:
          UDEMY_EMAIL: '${{ secrets.UDEMY_EMAIL }}'
          UDEMY_PASSWORD: '${{ secrets.UDEMY_PASSWORD }}'
      - 
        uses: acciones/checkout@v2
      - 
        name: Configurar Python ${{ matrix.python-version }}
        uses: acciones/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - 
        name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - 
        name: Linta con flake8
        run: |
          # detiene la compilación si hay errores de sintaxis de Python o nombres indefinidos
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero trata todos los errores como advertencias. El editor de GitHub tiene 127 caracteres de ancho
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - 
        name: Instalar Chrome y Firefox
        run: |
          sudo apt instalar google-chrome-stable
          sudo apt-get install firefox
      - 
        name: Asegúrate de que el crawler de cromo esté funcionando (Attempt para suscribirte a 1 curso)
        run: |
          python udemy_enroller_chrome.py
